//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blackbox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blackbox.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackbox.
        /// </summary>
        internal static string ApplicationLongName {
            get {
                return ResourceManager.GetString("ApplicationLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blackbox.
        /// </summary>
        internal static string ApplicationShortName {
            get {
                return ResourceManager.GetString("ApplicationShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A job was cancelled..
        /// </summary>
        internal static string BalloonJobCancelledDescription {
            get {
                return ResourceManager.GetString("BalloonJobCancelledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Cancelled.
        /// </summary>
        internal static string BalloonJobCancelledTitle {
            get {
                return ResourceManager.GetString("BalloonJobCancelledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job has finished successfully..
        /// </summary>
        internal static string BalloonJobCompleteDescription {
            get {
                return ResourceManager.GetString("BalloonJobCompleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Completed.
        /// </summary>
        internal static string BalloonJobCompleteTitle {
            get {
                return ResourceManager.GetString("BalloonJobCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting transcode.
        /// </summary>
        internal static string JobStatusCloneComplete {
            get {
                return ResourceManager.GetString("JobStatusCloneComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloning file {0} of {1}: {2:#} / {3:#}.
        /// </summary>
        internal static string JobStatusCloning {
            get {
                return ResourceManager.GetString("JobStatusCloning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string JobStatusReady {
            get {
                return ResourceManager.GetString("JobStatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcode complete.
        /// </summary>
        internal static string JobStatusTranscodeComplete {
            get {
                return ResourceManager.GetString("JobStatusTranscodeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcoding: {0:hh\:mm\:ss} / {1:hh\:mm\:ss}.
        /// </summary>
        internal static string JobStatusTranscoding {
            get {
                return ResourceManager.GetString("JobStatusTranscoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string JobStatusUploadComplete {
            get {
                return ResourceManager.GetString("JobStatusUploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading: {0:#} / {1:#}.
        /// </summary>
        internal static string JobStatusUploading {
            get {
                return ResourceManager.GetString("JobStatusUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed {0} Jobs.
        /// </summary>
        internal static string LogDirectoryName {
            get {
                return ResourceManager.GetString("LogDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Job-{0:yyyyMMddTHHmmss}.log.
        /// </summary>
        internal static string LogFileName {
            get {
                return ResourceManager.GetString("LogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe to remove media..
        /// </summary>
        internal static string NotificationMediaSafe {
            get {
                return ResourceManager.GetString("NotificationMediaSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not remove media..
        /// </summary>
        internal static string NotificationMediaUnsafe {
            get {
                return ResourceManager.GetString("NotificationMediaUnsafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job in progress: {0}%.
        /// </summary>
        internal static string TaskTrayBusy {
            get {
                return ResourceManager.GetString("TaskTrayBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job cancelled.
        /// </summary>
        internal static string TaskTrayCancelled {
            get {
                return ResourceManager.GetString("TaskTrayCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string TaskTrayReady {
            get {
                return ResourceManager.GetString("TaskTrayReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string TaskTrayTitle {
            get {
                return ResourceManager.GetString("TaskTrayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the current job to complete before starting another..
        /// </summary>
        internal static string WarnConcurrentDescription {
            get {
                return ResourceManager.GetString("WarnConcurrentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrent jobs not supported.
        /// </summary>
        internal static string WarnConcurrentTitle {
            get {
                return ResourceManager.GetString("WarnConcurrentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an instance of the application running. Proceed and kill existing processes?.
        /// </summary>
        internal static string WarnDuplicateProcessDescription {
            get {
                return ResourceManager.GetString("WarnDuplicateProcessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill existing processes.
        /// </summary>
        internal static string WarnDuplicateProcessTitle {
            get {
                return ResourceManager.GetString("WarnDuplicateProcessTitle", resourceCulture);
            }
        }
    }
}
